### ISSUE TITLE
Désactiver l'affichage des offres payantes

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-api#106]
On le réactivera au lancement.

**Comment by arnoo** [comment]
Idée pour ça : renvoyer None dans le scoring (dans score_offer de datascience/offers.py) dès qu'un des stocks a un amount pour cette offer. Mais pour qu'on puisse tester nous la gestion des sous il faudrait ne le faire que si (NOT IS_DEV).

**Comment by abel-andre** [comment]
On pourrait aussi ne pas renvoyer les offres qui ont des stocks avec amount *après* le scoring, comme ça on n'utilise la variable IS_DEV qu'au niveau de la route et ça se rapproche d'un feature flipping. Qu'en penses-tu ? (dans l'idée : un feature toggle n'est utilisé qu'à un nombre très restreint d'endroit, et à des endroits où ça coûte très peu cher de supprimer une fois qu'on en a plus besoin)

**Comment by arnoo** [comment]
J'aime bien le principe mais ca me semble plus compliqué.
