### ISSUE TITLE
Création de la venue "numérique"

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-api#119]
Ajouter une propriété "isVirtual" ou quelque chose comme ça sur l'objet venue. Il ne peut y en avoir qu'une avec isVirtual et un managingOfferer donné (contrainte BDD). Changer les contraintes sur les champs adresse : ils sont forcément =null si isVirtual, forcément !=null sinon.

Créer automatiquement la venue isVirtual à la création de l'offerer.

Écrire la migration BDD qui ajoute le champ isVirtual et crée la venue isVirtual pour chaque offerer existant.

**Comment by sofcalca** [comment]
Problème : lors de la création automatique de la venue, qu'est-ce qu'on met dans booking email ?

**Comment by arnoo** [comment]
Je dirais: on s'assure qu'on gère bien le cas ou bookingEmail = null et on le met à null (ce qui veut dire pas d'email lors du booking)
+ cf. https://github.com/betagouv/pass-culture-api/issues/130
