### ISSUE TITLE
Route d'annulation de booking

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-api#124]
Route delete booking qui met validUntilDatetime à now () ?

**Comment by abel-andre** [comment]
On a pas de champ validUntilDatetime aujourd'hui.
On pourrait en mettre un, mais on se dit que c'est la contremarque (champ) token qui a une validité plutôt que le booking.
Aussi, le token aura besoin d'être validé par les offreurs, on aurait donc plus besoin d'un validationToken (qui vient de la mixin) pour faire ça.
On a un champ isActive, mais on ne sait pas s'il c'est ça qu'il faut utiliser pour cette issue...

En bref => on est bloqué pour le moment pour implémenter ça, on a pas envie de prendre trop d'hypothèses hasardeuses :-/

**Comment by arnoo** [comment]
Doublon de https://github.com/betagouv/pass-culture-browser/issues/279

**Comment by arnoo** [comment]
En fait, pas un doublon !
