### ISSUE TITLE
[API] Ajouter bookingEmail sur offer

### ISSUE THREAD

**Issue by arnoo** [betagouv/pass-culture-api#130]
Ajouter un bookingEmail sur offer qui par défaut est null. Lors des envois de mails on remplace venue.bookingEmail offer.bookingEmail.

**Comment by sixertoy** [comment]
il s'agit de l'email auquel on enverra l'information d'une nouvelle inscription contenant le code de validation ?

**Comment by arnoo** [comment]
Non, c'est l'email sur lequel on envoie un mail lors des bookings.

**Comment by sofcalca** [comment]
On fait quoi si c'est null ? On n'envoie pas le mail au pro ou on l'envoie au mail de la venue quand même ?

**Comment by abel-andre** [comment]
Même question :)

**Comment by arnoo** [comment]
On envoie pas de mail (ça permet à l'offreur de demander à ne pas avoir de mails pour certaines offres).
